### ISSUE TITLE
Make sure the costs are correct for re-entrant calls

### ISSUE THREAD

**Issue by abizjak** [Concordium/concordium-smart-contract-tools#111]
**Task description**

We have changed/fixed the semantics of re-entrant calls in the node in P6.

We should make sure that the costs in the testing library are correct. In particular 

- [ ] add the re-entrant tests from the node to the tests of the library
- [ ] make sure that the library reports correct cost
- [ ] make sure the library then also reports correct "state has changed" back to the contract.
