### ISSUE TITLE
Implement reproducible builds in cargo-concordium

### ISSUE THREAD

**Issue by abizjak** [Concordium/concordium-smart-contract-tools#125]
**Task description**

- [x] Define Docker image to be used.
- [x] Add an option to use the docker image in cargo-concordium to build new contracts.
- [ ] Add an option to verify an existing archive using cargo-concordium
- [ ] Add the ability to update build info using cargo-concordium.
