### ISSUE TITLE
Collection for improvements/feature requests for the hosted init/deploy front end.

### ISSUE THREAD

**Issue by DOBEN** [Concordium/concordium-smart-contract-tools#131]
**Task description**

- [ ] Allow raw input parameter (without providing a valid schema). This can be useful for experienced smart contract developers that e.g uses some sort of proxy-implementation setup (where the e.g. proxy schema of a smart contract might not tell the complete picture about how to interact with the contract). This would also allow somebody to use a pre-serialized string, or to deploy a new instance from the parameters of a different init transaction without caring about the schema.[https://github.com/Concordium/concordium-smart-contract-tools/pull/123#discussion_r1382915205](https://github.com/Concordium/concordium-smart-contract-tools/pull/123#discussion_r1382915205)
- [ ] Add a dry-run step before executing a deploy/init/update transaction. Purpose: the user should be warned if the dry-run step concludes that the transaction will fail on chain (no transaction fees should be wasted by the user).
- [x] ~Have a hardcoded connection to a node as well that would allow people to use the ~`~read box~`~ even if they are not connected with a wallet to the side.~ Tracked by [https://github.com/Concordium/concordium-smart-contract-tools/issues/166](https://github.com/Concordium/concordium-smart-contract-tools/issues/166)
- [ ] Better error reporting if user uses a smart contract index that is too large.
- [ ] Better error handling. In particular, think about using the read box as a `simulation/dry-run` box.
  [https://github.com/Concordium/concordium-smart-contract-tools/pull/123#discussion_r1387772430](https://github.com/Concordium/concordium-smart-contract-tools/pull/123#discussion_r1387772430)
- [ ] Refactor: The text area used as input parameter should be its own component to avoid code duplication. The `inputParameterType` dropDown and the `inputParameter` field/textArea should be its own component to avoid code duplication.
- [ ] Refactor: Investigate `Controller` component, `Validation rules`, and if more `useEffects` would be beneficial for the purpose of reducing the `onChange` functions.
  [https://github.com/Concordium/concordium-smart-contract-tools/pull/123#discussion_r1382938633](https://github.com/Concordium/concordium-smart-contract-tools/pull/123#discussion_r1382938633)
