### ISSUE TITLE
Extract `ContractTraceElements` for failed calls in the testing lib

### ISSUE THREAD

**Issue by Bargsteen** [Concordium/concordium-smart-contract-tools#73]
**Task description**

This task relates to the testing library.

When contracts invoke certain host functions, for example calling another contract or transferring CCD, `ContractTraceElement`s are created. This is true both in the testing library and the node.
There are different kinds of trace elements. As an example, consider a contract call that transfers CCD to an account and then returns. It would produce the following trace elements:
- `Interrupted` the contract
- `Transferred` the CCD
- `Resumed` the contract after a successful interrupt
- `Updated` the contract with success

The trace elements record the high-level interactions in a contract call and are useful for testing and also debugging.
However, the debugging aspect could be improved because trace elements of inner calls that eventually fail are omitted.
This was originally by design in the node, but in the testing library, we can change this behavior to allow the user to get _all_ trace elements and use them for testing and debugging.

An example of trace elements being "lost" is the following:
- `Interrupted` contract `A` to call contract `B`.
    - `Interrupted contract `B`  <- omitted
    - `Transferred` CCD <- omitted
    - `Resumed` <- omitted
    - Then fail. (so there is no `Update`) <- omitted
- `Resumed` the contract **after a failed interrupt.**

In this example, all the trace elements of contract `B` are omitted, because the call eventually fails.
This task is about collecting and exposing the previously omitted trace elements in a nice way to the developer.

**Tasks**
- [ ] Collect all the trace elements instead of discarding them
- [ ] Find out how to expose it to the user (while still allowing the user to get the list as it is currently)
   - It should be easy to see _where_ the omitted events fit into the original list.
- [ ] Include trace elements in `ContractInvokeFailure`, for when the outer-most entrypoint fails.
- [ ] Write a few test cases that showcases the usefulness and tests the functionality.
